package za.co.urbaneye.reporthole.security;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.jspecify.annotations.NonNull;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;
import za.co.urbaneye.reporthole.device.entity.DashcamDevice;
import za.co.urbaneye.reporthole.device.repository.DashcamDeviceRepository;
import za.co.urbaneye.reporthole.user.entity.UserAuth;
import za.co.urbaneye.reporthole.user.entity.UserStatus;
import za.co.urbaneye.reporthole.user.repository.IUserAuthRepository;

import java.io.IOException;
import java.time.Instant;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.UUID;

/**
 * Spring Security filter responsible for processing authentication
 * on every incoming HTTP request.
 *
 * <p>This filter executes once per request and handles two token types
 * carried in the {@code Authorization: Bearer} header:</p>
 *
 * <ul>
 *     <li><b>JWT</b> — identified by containing exactly two dots
 *         (three Base64-encoded segments). Validated and parsed using {@link Jwt}.
 *         Accepted on all authenticated endpoints. Beyond signature and expiry, every
 *         JWT request also costs one cheap {@link UserAuth} lookup so the stateless
 *         token gets a stateful checkpoint: a non-{@code ACTIVE} account, or a token
 *         issued before the account's {@code credentialsValidFrom} watermark, is
 *         rejected with 401. This is what lets a {@code SECURITY_ADMIN} revoke roles,
 *         suspend accounts or force a logout and have it take effect immediately
 *         rather than whenever the token happens to expire.</li>
 *     <li><b>Device token</b> — a plain UUID string with no dots, generated by
 *         {@code POST /devices/token/generate}. Only accepted for
 *         {@code /incidents/**} endpoints so that dashcam devices cannot
 *         mint their own tokens or access other resources.</li>
 * </ul>
 *
 * <p>A fallback accepts the JWT via {@code ?token=} query param for SSE
 * connections, because {@code EventSource} cannot set custom headers.</p>
 *
 * <p>If no token is found the request continues unauthenticated and
 * Spring Security enforces access rules on the route level.</p>
 *
 * @author Refentse
 * @since 1.0
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class JwtAuthenticationFilter extends OncePerRequestFilter {

    private final Jwt jwt;
    private final DashcamDeviceRepository dashcamDeviceRepository;
    private final IUserAuthRepository userAuthRepository;

    /**
     * Intercepts each HTTP request and applies token-based authentication logic.
     *
     * @param request     incoming HTTP request
     * @param response    outgoing HTTP response
     * @param filterChain filter chain for continuing request processing
     * @throws ServletException if servlet processing fails
     * @throws IOException      if input/output errors occur
     */
    @Override
    protected void doFilterInternal(HttpServletRequest request,
                                    @NonNull HttpServletResponse response,
                                    @NonNull FilterChain filterChain)
            throws ServletException, IOException {

        if (request.getMethod().equalsIgnoreCase("OPTIONS")) {
            filterChain.doFilter(request, response);
            return;
        }

        log.info("[JWT-FILTER] {} {}", request.getMethod(), request.getServletPath());

        String authHeader = request.getHeader("Authorization");
        String token;

        if (authHeader != null && authHeader.startsWith("Bearer ")) {
            token = authHeader.substring(7);
        } else {
            String servletPath = request.getServletPath();
            String queryToken = request.getParameter("token");
            log.info("[JWT-FILTER] No auth header — path={} hasQueryToken={}", servletPath, queryToken != null);
            if (servletPath.endsWith("/incidents/events") && queryToken != null && !queryToken.isBlank()) {
                log.info("[JWT-FILTER] SSE fallback: authenticating via ?token=");
                authenticateWithJwt(queryToken, response, filterChain, request);
                return;
            }
            log.info("[JWT-FILTER] No token — passing through unauthenticated");
            filterChain.doFilter(request, response);
            return;
        }

        // JWTs always have exactly two dots (header.payload.signature).
        // Device tokens are plain UUIDs and contain no dots.
        long dotCount = token.chars().filter(c -> c == '.').count();

        if (dotCount == 2) {
            authenticateWithJwt(token, response, filterChain, request);
        } else {
            authenticateWithDeviceToken(token, request, response, filterChain);
        }
    }

    /**
     * Validates a JWT and, if valid, sets the Spring Security context with
     * the user ID and roles extracted from the token claims.
     *
     * @param token       raw JWT string (without "Bearer " prefix)
     * @param response    HTTP response — written to on validation failure
     * @param filterChain filter chain — called on success to continue processing
     * @param request     original HTTP request passed through to the filter chain
     */
    private void authenticateWithJwt(String token,
                                     HttpServletResponse response,
                                     FilterChain filterChain,
                                     HttpServletRequest request) throws IOException, ServletException {
        if (!jwt.isTokenValid(token)) {
            response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
            response.getWriter().write("Invalid or expired token");
            return;
        }

        String userId = jwt.extractUserId(token);

        // Stateful checkpoint for the stateless token: the account must still exist, still be
        // ACTIVE, and the token must have been issued no earlier than the account's
        // credentialsValidFrom watermark. A single indexed primary-key lookup per request.
        if (!isAccountUsable(userId, token, response)) {
            return;
        }

        List<String> roles = jwt.extractRoles(token);

        List<SimpleGrantedAuthority> authorities = (roles == null ? List.<String>of() : roles).stream()
                .map(role -> role.startsWith("ROLE_") ? role : "ROLE_" + role)
                .map(SimpleGrantedAuthority::new)
                .toList();

        UsernamePasswordAuthenticationToken authentication =
                new UsernamePasswordAuthenticationToken(userId, null, authorities);

        SecurityContextHolder.getContext().setAuthentication(authentication);
        System.out.println("AUTHENTICATED USER: " + authentication.getPrincipal());
        System.out.println("AUTHORITIES: " + authentication.getAuthorities());
        System.out.println("IS AUTHENTICATED: " + authentication.isAuthenticated());
        filterChain.doFilter(request, response);
    }

    /**
     * Confirms the account behind a signature-valid JWT is still allowed to authenticate.
     *
     * <p>Rejects the request (401, and writes a short reason) when:</p>
     * <ul>
     *     <li>the subject claim is not a well-formed UUID;</li>
     *     <li>no {@link UserAuth} row exists for it — the account was hard-deleted;</li>
     *     <li>the account status is anything other than {@link UserStatus#ACTIVE}
     *         (suspended, locked, soft-deleted, or still pending verification);</li>
     *     <li>the token was issued before the account's {@code credentialsValidFrom}
     *         watermark — i.e. a {@code SECURITY_ADMIN} has since revoked sessions,
     *         changed the role, or suspended and reactivated the account.</li>
     * </ul>
     *
     * <p>The {@code credentialsValidFrom} comparison is done at whole-second precision
     * because a JWT {@code iat} claim carries only seconds; a token minted in the same
     * second as the watermark bump is allowed through.</p>
     *
     * @param userId   the token subject claim (expected to be a user UUID)
     * @param token    the raw JWT, used to read its issued-at timestamp
     * @param response written to with the 401 status and reason on rejection
     * @return {@code true} if the account may proceed, {@code false} if the request was rejected
     */
    private boolean isAccountUsable(String userId, String token, HttpServletResponse response) throws IOException {
        UUID userUuid;
        try {
            userUuid = UUID.fromString(userId);
        } catch (IllegalArgumentException | NullPointerException e) {
            writeUnauthorized(response, "Malformed token subject");
            return false;
        }

        UserAuth account = userAuthRepository.findById(userUuid).orElse(null);
        if (account == null) {
            writeUnauthorized(response, "Account no longer exists");
            return false;
        }

        if (account.getStatus() != UserStatus.ACTIVE) {
            log.info("[JWT-FILTER] Rejecting token for account {} in status {}", userUuid, account.getStatus());
            writeUnauthorized(response, "Account is not active");
            return false;
        }

        Instant issuedAt = jwt.extractIssuedAt(token);
        if (account.getCredentialsValidFrom() != null && issuedAt != null) {
            Instant validFrom = account.getCredentialsValidFrom()
                    .truncatedTo(ChronoUnit.SECONDS)
                    .atZone(ZoneId.systemDefault())
                    .toInstant();
            if (issuedAt.isBefore(validFrom)) {
                log.info("[JWT-FILTER] Rejecting revoked session for account {} (issuedAt {} < validFrom {})",
                        userUuid, issuedAt, validFrom);
                writeUnauthorized(response, "Session has been revoked — please sign in again");
                return false;
            }
        }

        return true;
    }

    /**
     * Writes a 401 response with a plain-text reason, matching the style used elsewhere in this filter.
     *
     * @param response the servlet response
     * @param reason   short human-readable explanation
     */
    private void writeUnauthorized(HttpServletResponse response, String reason) throws IOException {
        response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
        response.getWriter().write(reason);
    }

    /**
     * Resolves a device token to the linked user account and sets the security
     * context, allowing the dashcam page to create incidents without a JWT login.
     *
     * <p>Device tokens are accepted only for {@code /incidents/**} paths.
     * Requests to any other path with a non-JWT Bearer token receive a 401,
     * which prevents dashcam devices from generating their own tokens or
     * accessing unrelated endpoints.</p>
     *
     * @param token       raw device token string (a UUID without dashes or a UUID string)
     * @param request     HTTP request — used to check the request path
     * @param response    HTTP response — written to on authentication failure
     * @param filterChain filter chain — called on success to continue processing
     */
    private void authenticateWithDeviceToken(String token,
                                             HttpServletRequest request,
                                             HttpServletResponse response,
                                             FilterChain filterChain) throws IOException, ServletException {
        // Device tokens are accepted for incident creation and async frame submission.
        // getServletPath() returns the path after the context-path prefix (/api/),
        // so "/api/incidents/create" becomes "/incidents/create" here.
        String servletPath = request.getServletPath();
        boolean isDeviceTokenPath = servletPath.startsWith("/incidents/")
                || servletPath.equals("/inference/frames");
        if (!isDeviceTokenPath) {
            response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
            response.getWriter().write("Device token not accepted for this endpoint");
            return;
        }

        DashcamDevice device = dashcamDeviceRepository.findByDeviceToken(token).orElse(null);
        if (device == null) {
            response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
            response.getWriter().write("Invalid device token");
            return;
        }

        // Authenticate as the linked user with CIVILIAN role
        String userId = device.getUser().getUserId().toString();
        List<SimpleGrantedAuthority> authorities = List.of(new SimpleGrantedAuthority("ROLE_CIVILIAN"));

        UsernamePasswordAuthenticationToken authentication =
                new UsernamePasswordAuthenticationToken(userId, null, authorities);

        SecurityContextHolder.getContext().setAuthentication(authentication);
        System.out.println("AUTHENTICATED DEVICE: " + userId);
        filterChain.doFilter(request, response);
    }
}