package za.co.urbaneye.reporthole.security;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import lombok.RequiredArgsConstructor;
import org.jspecify.annotations.NonNull;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;
import za.co.urbaneye.reporthole.device.entity.DashcamDevice;
import za.co.urbaneye.reporthole.device.repository.DashcamDeviceRepository;

import java.io.IOException;
import java.util.List;

/**
 * Spring Security filter responsible for processing authentication
 * on every incoming HTTP request.
 *
 * <p>This filter executes once per request and handles two token types
 * carried in the {@code Authorization: Bearer} header:</p>
 *
 * <ul>
 *     <li><b>JWT</b> — identified by containing exactly two dots
 *         (three Base64-encoded segments). Validated and parsed using {@link Jwt}.
 *         Accepted on all authenticated endpoints.</li>
 *     <li><b>Device token</b> — a plain UUID string with no dots, generated by
 *         {@code POST /devices/token/generate}. Only accepted for
 *         {@code /incidents/**} endpoints so that dashcam devices cannot
 *         mint their own tokens or access other resources.</li>
 * </ul>
 *
 * <p>A fallback accepts the JWT via {@code ?token=} query param for SSE
 * connections, because {@code EventSource} cannot set custom headers.</p>
 *
 * <p>If no token is found the request continues unauthenticated and
 * Spring Security enforces access rules on the route level.</p>
 *
 * @author Refentse
 * @since 1.0
 */
@Component
@RequiredArgsConstructor
public class JwtAuthenticationFilter extends OncePerRequestFilter {

    private final Jwt jwt;
    private final DashcamDeviceRepository dashcamDeviceRepository;

    /**
     * Intercepts each HTTP request and applies token-based authentication logic.
     *
     * @param request     incoming HTTP request
     * @param response    outgoing HTTP response
     * @param filterChain filter chain for continuing request processing
     * @throws ServletException if servlet processing fails
     * @throws IOException      if input/output errors occur
     */
    @Override
    protected void doFilterInternal(HttpServletRequest request,
                                    @NonNull HttpServletResponse response,
                                    @NonNull FilterChain filterChain)
            throws ServletException, IOException {

        if (request.getMethod().equalsIgnoreCase("OPTIONS")) {
            filterChain.doFilter(request, response);
            return;
        }

        String authHeader = request.getHeader("Authorization");
        String token;

        if (authHeader != null && authHeader.startsWith("Bearer ")) {
            token = authHeader.substring(7);
        } else {
            // Fallback: allow JWT as query param for SSE connections (EventSource can't set headers)
            String queryToken = request.getParameter("token");
            if (queryToken == null || queryToken.isBlank()) {
                filterChain.doFilter(request, response);
                return;
            }
            token = queryToken;
            // SSE fallback only supports JWTs — fall through to JWT validation below
            authenticateWithJwt(token, response, filterChain, request);
            return;
        }

        // JWTs always have exactly two dots (header.payload.signature).
        // Device tokens are plain UUIDs and contain no dots.
        long dotCount = token.chars().filter(c -> c == '.').count();

        if (dotCount == 2) {
            authenticateWithJwt(token, response, filterChain, request);
        } else {
            authenticateWithDeviceToken(token, request, response, filterChain);
        }
    }

    /**
     * Validates a JWT and, if valid, sets the Spring Security context with
     * the user ID and roles extracted from the token claims.
     *
     * @param token       raw JWT string (without "Bearer " prefix)
     * @param response    HTTP response — written to on validation failure
     * @param filterChain filter chain — called on success to continue processing
     * @param request     original HTTP request passed through to the filter chain
     */
    private void authenticateWithJwt(String token,
                                     HttpServletResponse response,
                                     FilterChain filterChain,
                                     HttpServletRequest request) throws IOException, ServletException {
        if (!jwt.isTokenValid(token)) {
            response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
            response.getWriter().write("Invalid or expired token");
            return;
        }

        String userId = jwt.extractUserId(token);
        List<String> roles = jwt.extractRoles(token);

        List<SimpleGrantedAuthority> authorities = (roles == null ? List.<String>of() : roles).stream()
                .map(role -> role.startsWith("ROLE_") ? role : "ROLE_" + role)
                .map(SimpleGrantedAuthority::new)
                .toList();

        UsernamePasswordAuthenticationToken authentication =
                new UsernamePasswordAuthenticationToken(userId, null, authorities);

        SecurityContextHolder.getContext().setAuthentication(authentication);
        System.out.println("AUTHENTICATED USER: " + authentication.getPrincipal());
        System.out.println("AUTHORITIES: " + authentication.getAuthorities());
        System.out.println("IS AUTHENTICATED: " + authentication.isAuthenticated());
        filterChain.doFilter(request, response);
    }

    /**
     * Resolves a device token to the linked user account and sets the security
     * context, allowing the dashcam page to create incidents without a JWT login.
     *
     * <p>Device tokens are accepted only for {@code /incidents/**} paths.
     * Requests to any other path with a non-JWT Bearer token receive a 401,
     * which prevents dashcam devices from generating their own tokens or
     * accessing unrelated endpoints.</p>
     *
     * @param token       raw device token string (a UUID without dashes or a UUID string)
     * @param request     HTTP request — used to check the request path
     * @param response    HTTP response — written to on authentication failure
     * @param filterChain filter chain — called on success to continue processing
     */
    private void authenticateWithDeviceToken(String token,
                                             HttpServletRequest request,
                                             HttpServletResponse response,
                                             FilterChain filterChain) throws IOException, ServletException {
        // Device tokens are scoped to incident creation only.
        // getServletPath() returns the path after the context-path prefix (/api/),
        // so "/api/incidents/create" becomes "/incidents/create" here.
        if (!request.getServletPath().startsWith("/incidents/")) {
            response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
            response.getWriter().write("Device token not accepted for this endpoint");
            return;
        }

        DashcamDevice device = dashcamDeviceRepository.findByDeviceToken(token).orElse(null);
        if (device == null) {
            response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
            response.getWriter().write("Invalid device token");
            return;
        }

        // Authenticate as the linked user with CIVILIAN role
        String userId = device.getUser().getUserId().toString();
        List<SimpleGrantedAuthority> authorities = List.of(new SimpleGrantedAuthority("ROLE_CIVILIAN"));

        UsernamePasswordAuthenticationToken authentication =
                new UsernamePasswordAuthenticationToken(userId, null, authorities);

        SecurityContextHolder.getContext().setAuthentication(authentication);
        System.out.println("AUTHENTICATED DEVICE: " + userId);
        filterChain.doFilter(request, response);
    }
}