jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: reporthole-be
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: health, info, metrics, env

server:
  servlet:
    context-path: /api/

web:
  aes:
    key: ENC(CCYnDahSahayz24eQ91czkfxDy9LJM/eZ70io7PhNUr4poer+SrCuCBiXoVtK/034YXcBn5Ww24cKnI+zB8wOSSGJPMZemSqUUR1kPmf1js=)
  jwt:
    key: ENC(nTVulF4SgS7kw3GMeke/fFPWEq0qOqSauLIvQTPBGMwj0avVTl28nIc+8djS7DqRTEwF3JfME2dG71OGqV0BQ4ZZXtBzFKHJEgNaVLUBjwHNgCegDz8ZXTK8RnfMoUPgPLIxmiCL8/DBm8J8q2wWL6LSJf7k4qBLwVqGH3bJu04=)
    expiration: 86400000

app:
  upload:
    dir: uploads/incidents
  base-url: http://localhost:8080/api
  features:
    email-verification-enabled: true

inference:
  model-path: classpath:models/Reporthole-v1.onnx
  discard-threshold: 0.65
  auto-log-threshold: 0.80

mail:
  from: reporthole.noreply@gmail.com
  verification-url: https://localhost:3000/verify?token=
  verification-subject: "Verify your Reporthole account"
  password-reset-url: https://localhost:3000/reset-password?token=
  password-reset-subject: "Reset your Reporthole password"
