spring:
  datasource:
    url: ENC(your-encrypted-value-here)
    username: ENC(your-encrypted-value-here)
    password: ENC(your-encrypted-value-here)

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

services:
  web:
    allowed:
      - http://localhost:3000,
      - http://192.168.*:3000,
      - http://10.*:3000,
      - http://172.*:3000