package za.co.urbaneye.reporthole.device.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import za.co.urbaneye.reporthole.device.dto.DeviceSummaryResponse;
import za.co.urbaneye.reporthole.device.dto.DeviceTokenResponse;
import za.co.urbaneye.reporthole.device.service.interfaces.IDeviceService;
import za.co.urbaneye.reporthole.global.entity.AppResponse;

import java.util.List;
import java.util.UUID;

/**
 * REST controller for dashcam device management.
 *
 * <p>Exposes an endpoint for authenticated users to generate a long-lived
 * device token that a dashcam device can use instead of a full JWT login.
 * The token is entered once on the device and stored locally.</p>
 *
 * <p>Base URL: <b>/devices</b></p>
 *
 * @author Refentse
 * @since 1.0
 */
@RestController
@RequestMapping("devices")
@RequiredArgsConstructor
@Tag(name = "Devices", description = "Endpoints for dashcam device registration and token management.")
public class DeviceController {

    private final IDeviceService deviceService;

    /**
     * Generates a new long-lived device token for the authenticated user.
     *
     * <p>Requires a valid user JWT in the {@code Authorization} header.
     * Device tokens (which carry no dots) are not accepted here — a dashcam
     * cannot mint its own tokens.</p>
     *
     * <p>Each call creates a new token, allowing one account to register
     * multiple physical dashcam devices.</p>
     *
     * @return the newly generated device token wrapped in {@link AppResponse}
     */
    @PostMapping("/token/generate")
    @Operation(
            summary = "Generate device token",
            description = "Generates a long-lived device token linked to the authenticated user. "
                    + "Enter this token once on the dashcam device — it replaces the normal login flow."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Token generated successfully"),
            @ApiResponse(responseCode = "401", description = "Not authenticated or device token used instead of JWT"),
            @ApiResponse(responseCode = "404", description = "Authenticated user account not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<AppResponse<DeviceTokenResponse>> generateToken() {
        String userId = (String) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        DeviceTokenResponse response = deviceService.generateToken(userId);
        return ResponseEntity.ok(AppResponse.ok(response));
    }

    /**
     * Lists every dashcam device the authenticated user has registered.
     *
     * <p>Each device is returned with a short, non-reversible preview of its
     * token (never the full value) plus its id, so the civilian can tell
     * their devices apart and revoke one via {@link #revokeToken}.</p>
     *
     * @return the caller's devices, wrapped in {@link AppResponse}
     */
    @GetMapping
    @Operation(
            summary = "List my dashcam devices",
            description = "Returns every device token generated by the authenticated user. The full token is "
                    + "never exposed again — only a short preview and the row id needed to revoke it."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Devices listed successfully"),
            @ApiResponse(responseCode = "401", description = "Not authenticated")
    })
    public ResponseEntity<AppResponse<List<DeviceSummaryResponse>>> listDevices() {
        String userId = (String) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        return ResponseEntity.ok(AppResponse.ok(deviceService.listDevices(userId)));
    }

    /**
     * Revokes a device token belonging to the authenticated user.
     *
     * <p>Use this when a physical dashcam device is lost, stolen, or being
     * decommissioned — the token immediately stops authenticating.</p>
     *
     * @param id the {@code DashcamDevice} row id to revoke
     * @return 204 No Content on success
     */
    @DeleteMapping("/token/{id}")
    @Operation(
            summary = "Revoke device token",
            description = "Permanently deletes a device token so it can no longer be used to authenticate. "
                    + "A user may only revoke their own device tokens."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "Token revoked successfully"),
            @ApiResponse(responseCode = "403", description = "Token belongs to another user"),
            @ApiResponse(responseCode = "404", description = "Token not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    public ResponseEntity<Void> revokeToken(@PathVariable UUID id) {
        String userId = (String) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        deviceService.revokeToken(userId, id);
        return ResponseEntity.noContent().build();
    }
}
