name: Build & Test

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build & Test
        run: |
          if [ -z "APPLICATION_NAME" ]; then
          echo "SECRET IS EMPTY"
          else
          echo "SECRET IS SET (length: ${#JASYPT_ENCRYPTOR_PASSWORD})"
          fi
          if [ -z "$JASYPT_ENCRYPTOR_PASSWORD" ]; then
            echo "SECRET IS EMPTY"
          else
            echo "SECRET IS SET (length: ${#JASYPT_ENCRYPTOR_PASSWORD})"
          fi
          mvn clean test -X -Dspring.profiles.active=local
        env:
          JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.JASYPT_MASTER_PASSWORD }}